- name: check service existence
  stat: path=/etc/init.d/apparmor
  register: apparmor_service

- name: stop service
  service: name=apparmor state=stopped
  when: apparmor_service.stat.exists

- name: remove service
  service: name=apparmor enabled=no
  when: apparmor_service.stat.exists

- name: remove package
  apt: name=apparmor state=absent purge=yes

- command: locale-gen ja_JP.UTF-8

- apt: pkg=ntp state=present update_cache=yes
- service: name=ntp state=started enabled=yes

- name: add apt-repository
  apt: name=software-properties-common state=latest

- apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - tmux
    - vim
    - zip

- sysctl: name=net.core.somaxconn value=65535
- sysctl: name=net.ipv4.ip_local_port_range value="16384 65535"
- sysctl: name=net.ipv4.tcp_fin_timeout value=10
- sysctl: name=net.ipv4.tcp_keepalive_time value=60
- sysctl: name=net.ipv4.tcp_keepalive_intvl value=5
- sysctl: name=net.ipv4.tcp_keepalive_probes value=3
- sysctl: name=net.ipv4.tcp_rfc1337 value=1
- sysctl: name=net.ipv4.tcp_syncookies value=1
- sysctl: name=net.ipv4.tcp_tw_reuse value=1
