- name: c.c.mite discord bot
  hosts: hobby
  remote_user: ubuntu
  gather_facts: true
  become: yes
  vars_files:
    - ./vaults/discord.yml
    - ./vaults/twitter.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: './roles/prelude' }
    - { role: './roles/discord' }
