- name: c.c.mite core protect slave
  hosts: replica
  remote_user: ubuntu
  gather_facts: true
  become: yes
  vars_files:
    - ./vaults/mariadb.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - { role: './roles/prelude' }
    - { role: './roles/mariadb' }
