---
- name: setup mariadb repo
  shell: curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash

- apt:
    pkg:
      - mariadb-server-10.4
      - python3-mysqldb
    state: present
    update_cache: yes

- mysql_user:
    name: ccmite
    host: '%'
    password: "{{ ccmite_password }}"
    priv: '*.*:ALL'
    state: present

- template:
    src: my.cnf
    dest: /etc/mysql/my.cnf
  notify: restart mariadb
